export const reunionConfig = {
  school: "青葉高等学校",
  graduationYear: "2015年度卒業生",
  title: "卒業10周年 同窓会",
  date: "2026.11.21 SAT",
  receptionTime: "17:30",
  startTime: "18:00",
  closeTime: "20:30",
  venue: "THE GARDEN HALL AOYAMA",
  address: "東京都港区北青山 2-8-44",
  phone: "03-1234-5678",
  access: "東京メトロ銀座線 外苑前駅 3番出口より徒歩3分",
  mapUrl: "https://www.google.com/maps/search/?api=1&query=%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%AF%E5%8C%BA%E5%8C%97%E9%9D%92%E5%B1%B1",
  fee: "お一人様 ¥8,000",
  payment: "当日受付にて現金でお支払いください",
  deadline: "2026年10月25日（日）",
  dressCode: "スマートカジュアル",
  contact: "幹事代表：山田 太郎 / reunion@example.com",
  teachers: "佐藤先生・田中先生が出席予定です",
  message: "皆様、いかがお過ごしでしょうか。\n卒業から10年という節目を迎え、このたび同窓会を開催する運びとなりました。\n懐かしい思い出話をしながら、楽しい時間を過ごしましょう。\n皆様とお会いできるのを楽しみにしております。",
  schedule: [
    { time: "17:30", label: "受付開始" },
    { time: "18:00", label: "開宴・乾杯" },
    { time: "18:30", label: "歓談・恩師からのご挨拶" },
    { time: "20:10", label: "記念撮影" },
    { time: "20:30", label: "お開き" },
  ],
} as const;
